name: Generate Datas

on:
  schedule: # execute every 24 hours
    - cron: "* */1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: generate-snake-game-from-github-contribution-grid
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: imtribute12
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: Platane/snk@v2.2.1

        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
